# Generated by Django 5.0.6 on 2025-09-21 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('tg_nik', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграмм ник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.DateTimeField(auto_now_add=True, verbose_name='Первая рассылка')),
                ('follow_up', models.DateTimeField()),
                ('periodicity', models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=15, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('created', 'создана'), ('launched', 'запущена'), ('completed', 'завершена')], default='created', max_length=15, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(to='mailing.client', verbose_name='Клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='mailing.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя попытка')),
                ('status', models.CharField(choices=[('success', 'успешно'), ('failed', 'не успешно')], default='failed', verbose_name='Статус попытки')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервиса')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.newsletter', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
    ]
